server:
  port: 9006

spring:
  application:
    name: BOOK-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/books_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect